apiVersion: v1
kind: Service
metadata:
  name: luis-load-balancer
  labels:
    app: climate-app
spec:
  type: LoadBalancer
  ports:
  - port: 8000
  selector:
    app: climate-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: climate-app
  labels:
    app: climate-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: climate-app
  template:
    metadata:
      labels:
        app: climate-app
    spec:
      containers:
      - name: climate-app
        image: lfcunha07/climate_app:latest
        ports:
        - containerPort: 8000
